import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

export const PLUGIN_ID = "paperclipai.plugin-ontology";

/**
 * Host-derived namespace schema name.
 * Derived by the host as plugin_<slug>_<sha256(pluginId)[:10]>.
 * For PLUGIN_ID above with namespaceSlug "ontology" this is
 * plugin_ontology_b62f8af3e9 (kept in sync with migrations/001_ontology.sql).
 */
export const ONTOLOGY_NAMESPACE_SCHEMA = "plugin_ontology_b62f8af3e9";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.1.0",
  displayName: "Ontology",
  description:
    "Ontology modeling plugin: domains, node/relation types, graph instances, and Postgres recursive-CTE path/impact queries.",
  author: "Coolie",
  categories: ["automation", "ui"],
  capabilities: [
    "api.routes.register",
    "database.namespace.migrate",
    "database.namespace.read",
    "database.namespace.write",
    "companies.read",
    "activity.log.write",
    "events.emit",
    "http.outbound",
    "agent.tools.register",
    "plugin.state.read",
    "plugin.state.write",
    "ui.page.register",
    "ui.sidebar.register",
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  database: {
    namespaceSlug: "ontology",
    migrationsDir: "migrations",
    coreReadTables: ["companies"],
  },
  tools: [
    {
      name: "queryOntology",
      displayName: "Query Ontology",
      description:
        "Query the company ontology graph. Modes: 'node' (look up one node by domain slug + node key), 'nodes' (list nodes in a domain), 'path' (shortest directed hop path between two nodes by key). Returns structured graph data an agent can reason over.",
      parametersSchema: {
        type: "object",
        properties: {
          mode: { type: "string", enum: ["node", "nodes", "path"] },
          domainSlug: { type: "string", description: "Ontology domain slug (e.g. 'orders')." },
          nodeKey: { type: "string", description: "Node key for mode 'node'." },
          sourceNodeKey: { type: "string", description: "Source node key for mode 'path'." },
          targetNodeKey: { type: "string", description: "Target node key for mode 'path'." },
          limit: { type: "number", description: "Max nodes for mode 'nodes' (default 100)." },
          maxDepth: { type: "number", description: "Max hops for mode 'path'." },
        },
        required: ["mode", "domainSlug"],
      },
    },
    {
      name: "simulateOntologyImpact",
      displayName: "Simulate Ontology Impact",
      description:
        "Simulate the blast radius of a node in the ontology graph: which nodes are reachable downstream (affected by) or upstream (depend on) a given node. Use before changing an entity to understand what it impacts.",
      parametersSchema: {
        type: "object",
        properties: {
          domainSlug: { type: "string", description: "Ontology domain slug." },
          nodeKey: { type: "string", description: "The node whose impact radius to compute." },
          direction: {
            type: "string",
            enum: ["downstream", "upstream"],
            description: "downstream = nodes affected by this node; upstream = nodes this node depends on.",
          },
          maxDepth: { type: "number", description: "Max traversal depth." },
        },
        required: ["domainSlug", "nodeKey"],
      },
    },
  ],
  apiRoutes: [
    {
      routeKey: "health",
      method: "GET",
      path: "/health",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-domains",
      method: "GET",
      path: "/domains",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-domain",
      method: "POST",
      path: "/domains",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "create-node",
      method: "POST",
      path: "/nodes",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "create-edge",
      method: "POST",
      path: "/edges",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "get-domain",
      method: "GET",
      path: "/domains/:domainId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "update-domain",
      method: "PATCH",
      path: "/domains/:domainId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-node-types",
      method: "GET",
      path: "/node-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-node-type",
      method: "POST",
      path: "/node-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-node-type",
      method: "PATCH",
      path: "/node-types/:nodeTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-node-type",
      method: "DELETE",
      path: "/node-types/:nodeTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-relation-types",
      method: "GET",
      path: "/relation-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-relation-type",
      method: "POST",
      path: "/relation-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-relation-type",
      method: "PATCH",
      path: "/relation-types/:relationTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "graph-snapshot",
      method: "GET",
      path: "/graph",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "transition-domain",
      method: "POST",
      path: "/domains/:domainId/transition",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "snapshot-domain",
      method: "POST",
      path: "/domains/:domainId/snapshots",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-domain-snapshots",
      method: "GET",
      path: "/domains/:domainId/snapshots",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-functions",
      method: "GET",
      path: "/functions",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-function",
      method: "POST",
      path: "/functions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-function",
      method: "PATCH",
      path: "/functions/:functionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-function",
      method: "DELETE",
      path: "/functions/:functionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-audit-logs",
      method: "GET",
      path: "/audit-logs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-interfaces",
      method: "GET",
      path: "/interfaces",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-interface",
      method: "POST",
      path: "/interfaces",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-interface",
      method: "PATCH",
      path: "/interfaces/:interfaceId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-action-types",
      method: "GET",
      path: "/action-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-action-type",
      method: "POST",
      path: "/action-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-action-type",
      method: "PATCH",
      path: "/action-types/:actionTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-action-type",
      method: "DELETE",
      path: "/action-types/:actionTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-cognition-jobs",
      method: "GET",
      path: "/cognition-jobs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "get-cognition-job",
      method: "GET",
      path: "/cognition-jobs/:jobId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-cognition-job",
      method: "POST",
      path: "/cognition-jobs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "transition-cognition-job",
      method: "POST",
      path: "/cognition-jobs/:jobId/transition",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-cognition-shards",
      method: "POST",
      path: "/cognition-jobs/:jobId/shards",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "set-cognition-draft",
      method: "POST",
      path: "/cognition-jobs/:jobId/draft",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "publish-cognition-job",
      method: "POST",
      path: "/cognition-jobs/:jobId/publish",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "ingest-cognition-shard",
      method: "POST",
      path: "/cognition-jobs/:jobId/ingest-shard",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-datasets",
      method: "GET",
      path: "/datasets",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-dataset",
      method: "POST",
      path: "/datasets",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-dataset",
      method: "PATCH",
      path: "/datasets/:datasetId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-connectors",
      method: "GET",
      path: "/connectors",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-connector",
      method: "POST",
      path: "/connectors",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-connector",
      method: "PATCH",
      path: "/connectors/:connectorId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-transforms",
      method: "GET",
      path: "/transforms",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-transform",
      method: "POST",
      path: "/transforms",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-transform",
      method: "PATCH",
      path: "/transforms/:transformId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-package-installs",
      method: "GET",
      path: "/package-installs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-package-install",
      method: "POST",
      path: "/package-installs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-business-systems",
      method: "GET",
      path: "/business-systems",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "get-business-system",
      method: "GET",
      path: "/business-systems/:systemId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-business-system",
      method: "POST",
      path: "/business-systems",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-business-system",
      method: "PATCH",
      path: "/business-systems/:systemId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-sub-projects",
      method: "GET",
      path: "/sub-projects",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-sub-project",
      method: "POST",
      path: "/sub-projects",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-sub-project",
      method: "PATCH",
      path: "/sub-projects/:subProjectId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    { routeKey: "list-prompt-templates", method: "GET", path: "/prompt-templates", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-prompt-template", method: "POST", path: "/prompt-templates", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-golden-datasets", method: "GET", path: "/golden-datasets", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-golden-dataset", method: "POST", path: "/golden-datasets", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-aip-logics", method: "GET", path: "/aip-logics", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-aip-logic", method: "POST", path: "/aip-logics", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-aip-logic", method: "PATCH", path: "/aip-logics/:logicId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-evals", method: "GET", path: "/evals", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-eval", method: "POST", path: "/evals", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-eval", method: "PATCH", path: "/evals/:evalId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-simulation-scenarios", method: "GET", path: "/simulation-scenarios", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-simulation-scenario", method: "POST", path: "/simulation-scenarios", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-simulation-scenario", method: "PATCH", path: "/simulation-scenarios/:scenarioId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-entity-sets", method: "GET", path: "/umodel/entity-sets", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-entity-set", method: "POST", path: "/umodel/entity-sets", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-entities", method: "GET", path: "/umodel/entities", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-entity", method: "POST", path: "/umodel/entities", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-umodel-entity", method: "PATCH", path: "/umodel/entities/:entityId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-links", method: "GET", path: "/umodel/links", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-link", method: "POST", path: "/umodel/links", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-telemetry", method: "GET", path: "/umodel/telemetry", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "record-umodel-telemetry", method: "POST", path: "/umodel/telemetry", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    {
      routeKey: "find-path",
      method: "GET",
      path: "/path",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "find-impact",
      method: "GET",
      path: "/impact",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    { routeKey: "list-capability-gaps", method: "GET", path: "/capability-gaps", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-capability-gap", method: "POST", path: "/capability-gaps", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "acquire-capability", method: "POST", path: "/capability-gaps/:gapId/acquire", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-capability-resolutions", method: "GET", path: "/capability-gaps/:gapId/resolutions", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
  ],
  ui: {
    slots: [
      {
        type: "sidebar",
        id: "ontology-sidebar",
        displayName: "Ontology",
        exportName: "SidebarLink",
        order: 40,
      },
      {
        type: "page",
        id: "ontology-page",
        displayName: "Ontology",
        exportName: "OntologyPage",
        routePath: "ontology",
      },
    ],
  },
};

export default manifest;
