import { ONTOLOGY_TOOLS } from "@paperclipai/ontology-core/mcp/tools.js";
import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";

export const PLUGIN_ID = "paperclipai.plugin-ontology";

/**
 * Host-derived namespace schema name.
 * Derived by the host as plugin_<slug>_<sha256(pluginId)[:10]>.
 * For PLUGIN_ID above with namespaceSlug "ontology" this is
 * plugin_ontology_b62f8af3e9 (kept in sync with migrations/001_ontology.sql).
 */
export const ONTOLOGY_NAMESPACE_SCHEMA = "plugin_ontology_b62f8af3e9";

const manifest: PaperclipPluginManifestV1 = {
  id: PLUGIN_ID,
  apiVersion: 1,
  version: "0.1.0",
  displayName: "Ontology",
  description:
    "Ontology modeling plugin: domains, node/relation types, graph instances, and Postgres recursive-CTE path/impact queries.",
  author: "Coolie",
  categories: ["automation", "ui"],
  capabilities: [
    "api.routes.register",
    "database.namespace.migrate",
    "database.namespace.read",
    "database.namespace.write",
    "companies.read",
    // Read-only project metadata, so a project page can be linked to a domain
    // and the suggestion pass can use real project / workspace names.
    "projects.read",
    "activity.log.write",
    "events.emit",
    "http.outbound",
    "agent.tools.register",
    "plugin.state.read",
    "plugin.state.write",
    "ui.page.register",
    "ui.sidebar.register",
  ],
  entrypoints: {
    worker: "./dist/worker.js",
    ui: "./dist/ui",
  },
  database: {
    namespaceSlug: "ontology",
    migrationsDir: "migrations",
    coreReadTables: ["companies"],
  },
  // Derived from the core's catalogue rather than maintained here: a tool
  // declared but not handled, or handled but not declared, is a call an agent
  // cannot make. `tests/mcp-tools.spec.ts` binds the catalogue to the contract.
  tools: ONTOLOGY_TOOLS.map((tool) => ({
    name: tool.name,
    displayName: tool.displayName,
    description: tool.description,
    parametersSchema: tool.parametersSchema,
  })) as NonNullable<PaperclipPluginManifestV1["tools"]>,
  apiRoutes: [
    {
      routeKey: "health",
      method: "GET",
      path: "/health",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    // --- who may act --------------------------------------------------------
    // Identity management is board-only. `create-tenant` and `list-tenants` are
    // instance-scoped in a standalone deployment and still carry a company here,
    // because the host scopes every route that way.
    {
      routeKey: "create-tenant",
      method: "POST",
      path: "/tenants",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-tenants",
      method: "GET",
      path: "/tenants",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-api-key",
      method: "POST",
      path: "/api-keys",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-api-keys",
      method: "GET",
      path: "/api-keys",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "revoke-api-key",
      method: "POST",
      path: "/api-keys/revoke",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "create-member",
      method: "POST",
      path: "/members",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-members",
      method: "GET",
      path: "/members",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "update-member",
      method: "POST",
      path: "/members/update",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "remove-member",
      method: "POST",
      path: "/members/remove",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },

    {
      routeKey: "list-domains",
      method: "GET",
      path: "/domains",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-domain",
      method: "POST",
      path: "/domains",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "create-node",
      method: "POST",
      path: "/nodes",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "create-edge",
      method: "POST",
      path: "/edges",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "get-domain",
      method: "GET",
      path: "/domains/:domainId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "update-domain",
      method: "PATCH",
      path: "/domains/:domainId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-domain",
      method: "DELETE",
      path: "/domains/:domainId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-node-types",
      method: "GET",
      path: "/node-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-node-type",
      method: "POST",
      path: "/node-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-node-type",
      method: "PATCH",
      path: "/node-types/:nodeTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-node-type",
      method: "DELETE",
      path: "/node-types/:nodeTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-relation-types",
      method: "GET",
      path: "/relation-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-relation-type",
      method: "POST",
      path: "/relation-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-relation-type",
      method: "PATCH",
      path: "/relation-types/:relationTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-relation-type",
      method: "DELETE",
      path: "/relation-types/:relationTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "graph-snapshot",
      method: "GET",
      path: "/graph",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "get-domain-snapshot",
      method: "GET",
      path: "/domains/:domainId/snapshot",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "transition-domain",
      method: "POST",
      path: "/domains/:domainId/transition",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "set-domain-lifecycle",
      method: "POST",
      path: "/domains/:domainId/lifecycle",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "snapshot-domain",
      method: "POST",
      path: "/domains/:domainId/snapshots",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-domain-snapshots",
      method: "GET",
      path: "/domains/:domainId/snapshots",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-functions",
      method: "GET",
      path: "/functions",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-function",
      method: "POST",
      path: "/functions",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-function",
      method: "PATCH",
      path: "/functions/:functionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-function",
      method: "DELETE",
      path: "/functions/:functionId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-audit-logs",
      method: "GET",
      path: "/audit-logs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-interfaces",
      method: "GET",
      path: "/interfaces",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-interface",
      method: "POST",
      path: "/interfaces",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-interface",
      method: "PATCH",
      path: "/interfaces/:interfaceId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-interface",
      method: "DELETE",
      path: "/interfaces/:interfaceId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-action-types",
      method: "GET",
      path: "/action-types",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-action-type",
      method: "POST",
      path: "/action-types",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-action-type",
      method: "PATCH",
      path: "/action-types/:actionTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-action-type",
      method: "DELETE",
      path: "/action-types/:actionTypeId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-cognition-jobs",
      method: "GET",
      path: "/cognition-jobs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "get-cognition-job",
      method: "GET",
      path: "/cognition-jobs/:jobId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-cognition-job",
      method: "POST",
      path: "/cognition-jobs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "transition-cognition-job",
      method: "POST",
      path: "/cognition-jobs/:jobId/transition",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-cognition-shards",
      method: "POST",
      path: "/cognition-jobs/:jobId/shards",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "set-cognition-draft",
      method: "POST",
      path: "/cognition-jobs/:jobId/draft",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "publish-cognition-job",
      method: "POST",
      path: "/cognition-jobs/:jobId/publish",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "ingest-cognition-shard",
      method: "POST",
      path: "/cognition-jobs/:jobId/ingest-shard",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-datasets",
      method: "GET",
      path: "/datasets",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-dataset",
      method: "POST",
      path: "/datasets",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-dataset",
      method: "PATCH",
      path: "/datasets/:datasetId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-connectors",
      method: "GET",
      path: "/connectors",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-connector",
      method: "POST",
      path: "/connectors",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-connector",
      method: "PATCH",
      path: "/connectors/:connectorId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-transforms",
      method: "GET",
      path: "/transforms",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-transform",
      method: "POST",
      path: "/transforms",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-transform",
      method: "PATCH",
      path: "/transforms/:transformId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      // Both handlers existed in the worker's dispatch with no declaration, so
      // they answered the bridge but returned "Unknown ontology route" over
      // HTTP — reachable from the workbench, invisible to any API consumer.
      routeKey: "run-transform",
      method: "POST",
      path: "/transforms/:transformId/run",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "extract-document",
      method: "POST",
      path: "/documents/extract",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      // Answers "would this document load, and is it any good" without writing
      // anything. The control plane's build-spec planner calls this before it
      // lets a human approve a spec, so an unresolvable model is caught while it
      // is still a proposal. `validateDocument` is the single authority on the
      // vocabulary; the host does not restate it.
      routeKey: "validate-document",
      method: "POST",
      path: "/documents/validate",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      // The write side of the same document: an approved spec becomes a domain,
      // its object types and its relation types. Idempotent on the document's
      // slug, and it refuses a slug that a hand-made domain already holds rather
      // than overwriting it.
      routeKey: "import-document",
      method: "POST",
      path: "/documents/import",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-package-installs",
      method: "GET",
      path: "/package-installs",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-package-install",
      method: "POST",
      path: "/package-installs",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      // The proposal path. An agent may write a *proposal* — which changes
      // nothing until it is decided — so this one is open to `board-or-agent`
      // while deciding it is not.
      routeKey: "create-proposal",
      method: "POST",
      path: "/proposals",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      // The diagram as data. An agent fetches this and renders it with the
      // Archify skill; the workbench hands the same document to the user as a
      // file. Nothing is stored — a diagram is a product of the ontology, and
      // keeping it would make a second place where the architecture is described.
      routeKey: "architecture-diagram",
      method: "GET",
      path: "/architecture-diagram",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-views",
      method: "GET",
      path: "/views",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-view",
      method: "POST",
      path: "/views",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-view",
      method: "PATCH",
      path: "/views/:viewId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "delete-view",
      method: "DELETE",
      path: "/views/:viewId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "decide-proposal",
      method: "POST",
      path: "/proposals/:proposalId/decision",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-proposals",
      method: "GET",
      path: "/proposals",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "list-business-systems",
      method: "GET",
      path: "/business-systems",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "get-business-system",
      method: "GET",
      path: "/business-systems/:systemId",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-business-system",
      method: "POST",
      path: "/business-systems",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-business-system",
      method: "PATCH",
      path: "/business-systems/:systemId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "list-sub-projects",
      method: "GET",
      path: "/sub-projects",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "create-sub-project",
      method: "POST",
      path: "/sub-projects",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    {
      routeKey: "update-sub-project",
      method: "PATCH",
      path: "/sub-projects/:subProjectId",
      auth: "board",
      capability: "api.routes.register",
      companyResolution: { from: "body", key: "companyId" },
    },
    { routeKey: "list-prompt-templates", method: "GET", path: "/prompt-templates", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-prompt-template", method: "POST", path: "/prompt-templates", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-golden-datasets", method: "GET", path: "/golden-datasets", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-golden-dataset", method: "POST", path: "/golden-datasets", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-aip-logics", method: "GET", path: "/aip-logics", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-aip-logic", method: "POST", path: "/aip-logics", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-aip-logic", method: "PATCH", path: "/aip-logics/:logicId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-evals", method: "GET", path: "/evals", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-eval", method: "POST", path: "/evals", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-eval", method: "PATCH", path: "/evals/:evalId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-simulation-scenarios", method: "GET", path: "/simulation-scenarios", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-simulation-scenario", method: "POST", path: "/simulation-scenarios", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-simulation-scenario", method: "PATCH", path: "/simulation-scenarios/:scenarioId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-entity-sets", method: "GET", path: "/umodel/entity-sets", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-entity-set", method: "POST", path: "/umodel/entity-sets", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-entities", method: "GET", path: "/umodel/entities", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-entity", method: "POST", path: "/umodel/entities", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "update-umodel-entity", method: "PATCH", path: "/umodel/entities/:entityId", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-links", method: "GET", path: "/umodel/links", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-umodel-link", method: "POST", path: "/umodel/links", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-umodel-telemetry", method: "GET", path: "/umodel/telemetry", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "record-umodel-telemetry", method: "POST", path: "/umodel/telemetry", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    {
      routeKey: "find-path",
      method: "GET",
      path: "/path",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    {
      routeKey: "find-impact",
      method: "GET",
      path: "/impact",
      auth: "board-or-agent",
      capability: "api.routes.register",
      companyResolution: { from: "query", key: "companyId" },
    },
    { routeKey: "list-capability-gaps", method: "GET", path: "/capability-gaps", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
    { routeKey: "create-capability-gap", method: "POST", path: "/capability-gaps", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "acquire-capability", method: "POST", path: "/capability-gaps/:gapId/acquire", auth: "board", capability: "api.routes.register", companyResolution: { from: "body", key: "companyId" } },
    { routeKey: "list-capability-resolutions", method: "GET", path: "/capability-gaps/:gapId/resolutions", auth: "board-or-agent", capability: "api.routes.register", companyResolution: { from: "query", key: "companyId" } },
  ],
  ui: {
    slots: [
      {
        type: "sidebar",
        id: "ontology-sidebar",
        displayName: "Ontology",
        exportName: "SidebarLink",
        order: 40,
      },
      {
        type: "page",
        id: "ontology-page",
        displayName: "Ontology",
        exportName: "OntologyPage",
        routePath: "ontology",
        // The workbench is a full-bleed canvas surface: it needs a definite
        // height from the host so its `h-full` chain resolves instead of
        // collapsing to content height.
        layout: "fill",
      },
    ],
  },
};

export default manifest;
