/**
 * withLocalCleartextAllowlist — expo config plugin (wave285-C4)
 *
 * 阻断点 (docs-coolie/evidence/wave286/QA-REPORT.md §5.2-2): release 清单禁明文
 * HTTP, 装机指向 dev instance (模拟器 10.0.2.2:3100 / adb reverse localhost:3100)
 * 一律 Network request failed, 原生走查无法取证登录。
 *
 * 本插件给 Android 注入 networkSecurityConfig:
 * - main: base 保持禁明文 (生产行为不变), 仅对 10.0.2.2 / localhost / 127.0.0.1
 *   三个本地 dogfood 地址放行 cleartext;
 * - debug: 全量放行 (等效原 usesCleartextTraffic="true"; NSC 一旦存在会压过
 *   debug 清单的 usesCleartextTraffic 属性, 不放开会打断 metro JS 加载)。
 *
 * android/ 是 prebuild 产物 (gitignore); 本地已按插件产物手工同步, 下次
 * `npx expo prebuild -p android` 由本插件再生。
 */
const {
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

const LOCAL_HOSTS = ["10.0.2.2", "localhost", "127.0.0.1"];

const MAIN_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by withLocalCleartextAllowlist — release 保持禁明文, 仅放行本地 dogfood 地址 -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false" />
    <domain-config cleartextTrafficPermitted="true">
${LOCAL_HOSTS.map((h) => `        <domain includeSubdomains="false">${h}</domain>`).join("\n")}
    </domain-config>
</network-security-config>
`;

const DEBUG_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by withLocalCleartextAllowlist — debug 全量放行, 等效 usesCleartextTraffic="true" -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
`;

function writeXml(projRoot, variant, xml) {
  const dir = path.join(
    projRoot,
    "android",
    "app",
    "src",
    variant,
    "res",
    "xml",
  );
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "network_security_config.xml"), xml);
}

const withNetworkSecurityConfigFiles = (config) =>
  withDangerousMod(config, [
    "android",
    (mod) => {
      writeXml(mod.modRequest.projectRoot, "main", MAIN_XML);
      writeXml(mod.modRequest.projectRoot, "debug", DEBUG_XML);
      return mod;
    },
  ]);

const withManifestAttribute = (config) =>
  withAndroidManifest(config, (mod) => {
    const app = mod.modResults.manifest.application?.[0];
    if (app) {
      app.$["android:networkSecurityConfig"] = "@xml/network_security_config";
    }
    return mod;
  });

module.exports = (config) => withManifestAttribute(withNetworkSecurityConfigFiles(config));
