export { CoolieClient, CoolieApiError, isAsrNotConfigured } from "./client";
export type { CoolieClientOptions } from "./client";
export {
  isBoardChatStatusLine,
  isRenderableBoardMessage,
} from "./board-chat";
export {
  ASR_NOT_CONFIGURED,
  MULTIMODAL_PLUGIN_ID,
  ONTOLOGY_PLUGIN_ID,
} from "./types";
export {
  DEFAULT_WORK_MODE,
  WORK_MODES,
  WORK_MODE_OPTIONS,
  isSelectableWorkMode,
  workModeMetaFor,
  workModeOptions,
} from "./work-modes";
export type { IssueWorkMode, WorkModeMeta } from "./work-modes";
export {
  assigneeValueFromSelection,
  currentUserAssigneeOption,
  isAgentTaskTarget,
  parseAssigneeValue,
} from "./assignees";
export type { AssigneeOption, AssigneeSelection } from "./assignees";
export {
  ISSUE_OVERRIDE_ADAPTER_TYPES,
  buildAssigneeAdapterOverrides,
} from "./issue-assignee-overrides";
export type { BuildAssigneeAdapterOverridesInput, IssueModelLane } from "./issue-assignee-overrides";
export {
  buildExecutionPolicy,
  principalFromSelectionValue,
  selectionValueFromPrincipal,
} from "./issue-execution-policy";
export type {
  IssueExecutionPolicy,
  IssueExecutionStage,
  IssueExecutionStageParticipant,
  IssueExecutionStagePrincipal,
  IssueExecutionStageType,
} from "./issue-execution-policy";
export {
  EXECUTION_WORKSPACE_MODES,
  ISSUE_THINKING_EFFORT_OPTIONS,
  assigneeOptionsTitleFor,
  thinkingEffortOptionsFor,
} from "./issue-composer-options";
export type { ComposerOption, ProjectExecutionWorkspacePolicy } from "./issue-composer-options";
export {
  DEFAULT_TRUST_PRESET,
  LOW_TRUST_REVIEW_PRESET,
  TRUST_PRESETS,
  TRUST_PRESET_DESCRIPTION,
  TRUST_PRESET_LABEL,
  getTrustPreset,
} from "./trust";
export type { TrustPreset } from "./trust";
export type {
  AdapterModel,
  IssuePriority,
  IssueStatus,
  IssueSpecKind,
  Agent,
  AgentIdentity,
  AgentPermissions,
  IssueLabel,
  Company,
  Issue,
  SessionUser,
  CreateIssueInput,
  Project,
  ProjectDocument,
  ProjectDocumentAnalysis,
  ProjectDocumentUpload,
  IssueWbsType,
  MilestoneStatus,
  CmmiGateKey,
  IssueMilestone,
  ProjectWbsDraft,
  ProjectWbsDraftItem,
  WbsGateState,
  WbsMainline,
  WbsMainlineMilestone,
  WbsMainlinePhase,
  ProjectWbsView,
  ProjectWbsAdoption,
  UploadFilePart,
  AudioFormat,
  VoiceDispatchInput,
  VoiceDispatchResult,
  QuotaMetric,
  ProgressMetric,
  AgentHeartbeatInfo,
  IdleMetric,
  DeliveryCycleBucket,
  DeliveryCycleMetric,
  DailyThroughput,
  EfficiencyMetric,
  FailureRateMetric,
  CockpitDashboardMetrics,
  DashboardSummary,
  WorkspaceDiffView,
  WorkspaceDiffFileStatus,
  WorkspaceDiffPatchKind,
  WorkspaceDiffWarningCode,
  WorkspaceDiffWarning,
  WorkspaceDiffCaps,
  WorkspaceDiffFilePatch,
  WorkspaceDiffFile,
  WorkspaceDiffStats,
  WorkspaceDiffResponse,
  GetWorkspaceDiffParams,
  ExecutionWorkspace,
  IssueWorkProduct,
  OntologyDomainLifecycleState,
  OntologyDomain,
  OntologyGraphCounts,
  OntologyGraphNode,
  OntologyGraphEdge,
  OntologyGraphSnapshot,
  OntologyGraphResponse,
  OntologyGraphResponseNode,
  OntologyGraphResponseEdge,
  OntologyInstanceRow,
  OntologyInstancesResponse,
  OntologyPropertyEntry,
  OntologyPropertiesResponse,
  // wave261: drilldown summary
  OntologyEntityTypeLevel,
  OntologyDomainLevel,
  OntologyLevelsResponse,
  OntologyStatsResponse,
  OntologyTypeCount,
  // wave342: 本体工作台只读视图要渲染的行类型 (types.ts wave333/335 已
  // 定义, 供 client.ts 内部使用; 原生 App 的 14 视图组同样需要, 补导出)
  OntologyNodeType,
  OntologyRelationType,
  OntologyActionType,
  OntologyFunction,
  OntologyInterface,
  OntologyDataset,
  OntologyConnector,
  OntologyTransform,
  SetDomainLifecycleOptions,
  CompanyArtifactSource,
  CompanyArtifactMediaKind,
  CompanyArtifactGroupBy,
  CompanyArtifactIssueSummary,
  CompanyArtifactProjectSummary,
  CompanyArtifactAgentSummary,
  CompanyArtifactVersionSummary,
  CompanyArtifact,
  CompanyArtifactGroup,
  CompanyArtifactsResponse,
  WorkProductVersion,
  WorkProductVersionsResponse,
  ActivateWorkProductVersionResponse,
  CompanyArtifactsQuery,
  IssueAttachment,
  RuntimeExposureStatus,
  WorkspaceRuntimeService,
  BoardChatMessage,
  BoardChatStreamInput,
  BoardChatStreamEvent,
  BoardChatStreamCallbacks,
  BoardConversation,
  ApprovalStatus,
  Approval,
  ApprovalComment,
  ResolveApprovalOptions,
  ListApprovalsOptions,
  InboxApprovalItem,
  InboxFailureItem,
  InboxMentionItem,
  InboxFeed,
  GitProvider,
  GitCredential,
  SaveGitCredentialInput,
  PluginRecord,
  PluginStatus,
  PluginConfig,
  PluginConfigField,
  GovernanceGateCheck,
  GovernanceGate,
  GovernanceSummary,
  OntologyResourceKind,
  OntologyResourceRole,
  OntologyResourceLink,
  LinkOntologyResourceInput,
  UnlinkOntologyResourceInput,
} from "./types";

